$(document).ready(function(){
    $(".has-children").click(function(){
        $(this).toggleClass("open");
        $(this).find(".sub-menu").slideToggle();
    });
    $("#section-nav").find("li").hover(function(){
        $(this).find(".label").slideToggle();
    });
});
