$(document).ready(function(){
    $(".has-children").click(function(){
        $(this).toggleClass("open");
        $(this).find(".sub-menu").slideToggle();
    });
    $("#section-nav").find("li").hoverIntent(function(){
        $(this).find(".label").slideToggle(300);
    });
});
